services:
  - type: web
    name: a1-bedsheets-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: a1-bedsheets-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "A1 Bedsheets <noreply@a1bedsheets.ae>"
      - key: CLOUDINARY_URL
        sync: false
      - key: BASE_URL
        value: https://www.a1bedsheets.ae
      - key: FRONTEND_URL
        value: https://www.a1bedsheets.ae

databases:
  - name: a1-bedsheets-db
    plan: free
    databaseName: a1bedsheets
    user: a1bedsheets_user